### ISSUE TITLE
TypeError: 'NoneType' object is not callable

### ISSUE THREAD

**Issue by kotowick** [dtnewman/zappa_boilerplate#1]
Hi there,

I am getting this issue after deploying (note, the app runs fine locally):

`"{u'message': u'An uncaught exception happened while servicing this request. You can investigate this with the `zappa tail` command.', u'traceback': ['Traceback (most recent call last):\\n', '  File \"/var/task/handler.py\", line 448, in handler\\n    response = Response.from_app(self.wsgi_app, environ)\\n', '  File \"/private/var/folders/cb/qwdcqhtx04l9s1b1wmnfsg140000gn/T/pip-build-ec5u35/Werkzeug/werkzeug/wrappers.py\", line 903, in from_app\\n', '  File \"/private/var/folders/cb/qwdcqhtx04l9s1b1wmnfsg140000gn/T/pip-build-ec5u35/Werkzeug/werkzeug/wrappers.py\", line 57, in _run_wsgi_app\\n', '  File \"/private/var/folders/cb/qwdcqhtx04l9s1b1wmnfsg140000gn/T/pip-build-ec5u35/Werkzeug/werkzeug/test.py\", line 884, in run_wsgi_app\\n', \"TypeError: 'NoneType' object is not callable\\n\"]}"`

Any ideas @dtnewman ?

**Comment by dtnewman** [comment]
Hi @kotowick. Can you give me some more info to recreate this bug? What did you do after deploying that caused this issue?

EDIT: can you also share your zappa_settings.json file? This might help me diagnose this further.

**Comment by dtnewman** [comment]
bump (@kotowick). I'm unable to get recreate this issue. Please see above.

**Comment by dtnewman** [comment]
No reponse after several months. Closing this issue.
